"use client";
import "./globals.css";

import localFont from "next/font/local";
const myFont = localFont({
  src: "./font/IRANSans.ttf",
  display: "swap",
});

import Header from "./header/header";
import { useRef } from "react";
import useStore from "./store/store.jsx";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const ss=useStore((state)=>state.ss)
  const head=useStore((state)=>state.head)
  // const sT=useStore((state)=>state.sT)

  function scroll(e){
    const st=e.target.scrollTop
    // console.log(st);
    ss(st)
    if(st<200){
      head(st)
    }else if(st>200){
      head(0)
    }
  }
  

  return (
    <html lang="en" >
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={myFont.className}>
        <div className="w-[100%] h-[100vh] overflow-hidden">
          <div className="w-[100%] scroll h-[100%] overflow-y-scroll" onScroll={()=>scroll(event)}>
          <Header />
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
